image: php:7.1-cli
clone:
  depth: 1
pipelines:
  branches:
    master:
      - step:
          name: Preparing build artefacts
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - git config --global user.email "you@test.com"
            - git config --global user.name "Your Name"
            - ./vendor/bin/phing setup:seed-file -buildfile build.test.xml
            - ./vendor/bin/phing seed:drupal8 -Ddir.build=$(PWD)/build/default-d8
          artifacts:
            - build/**
      - step:
          name: Validate builds
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - ls -la build/default-d8
            - ./vendor/bin/phpunit tests/phpunit/DefaultDrupal8
definitions:
  services:
    selenium:
      image: selenium/standalone-firefox-debug:2.53.1-beryllium
    mysql:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: root
