image: php:7.1-cli
clone:
  depth: 1
pipelines:
  branches:
    master:
      - step:
          name: Prepare default build
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - ./vendor/bin/phing setup:seed-file -buildfile build.test.xml
            - ./vendor/bin/phing seed:drupal8
          artifacts:
            - build/**
      - step:
          name: Validate codebase data
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - ./vendor/bin/phpunit tests/phpunit/Seeder
definitions:
  services:
    selenium:
      image: selenium/standalone-firefox-debug:2.53.1-beryllium
    mysql:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: root
