image: php:7.1-cli
clone:
  depth: 1
pipelines:
  branches:
    master:
      - step:
          name: Preparing build artefacts
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - git config --global user.email "you@test.com"
            - git config --global user.name "Your Name"
            - ./vendor/bin/phing setup:seed-file -buildfile build.test.xml
            - ./vendor/bin/phing seed:drupal8 -Ddir.build=/opt/atlassian/pipelines/agent/build/build/default-d8
          artifacts:
            - build/**
      - step:
          name: Validate seeder builds
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - composer install
            - ./vendor/bin/phpunit tests/phpunit/DefaultDrupal8
          artifacts:
            - build/**
      - step:
          name: Validate filebased phing commands
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - echo "@TODO"
          artifacts:
            - build/**
      - step:
          name: Validate heavyD commands
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - echo "@TODO - Should run all the differen (non install connected heavyD commands)"
          artifacts:
            - build/**
      - step:
          name: Validate project setup
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - echo "@TODO - Should run project install and all the connected default behats"
          artifacts:
            - build/**
      - step:
          name: Validate project phing
          caches:
            - composer
          # @TODO Setup a more optimized container.
          image: surangagamage/heavyd-php-apache:7.1
          script:
            - echo "@TODO - Should runs all the phing commands that require the project to be installed."
          artifacts:
            - build/**
definitions:
  services:
    selenium:
      image: selenium/standalone-firefox-debug:2.53.1-beryllium
    mysql:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: root
