<?php

namespace Deployer;

set('ssh_type', 'native');
set('ssh_multiplexing', TRUE);

// This is loaded in by the deployer.phar and is accessible.
use Deployer\Task\Context;

/*
 * Set a basic set of properties based on the information in the /properties
 * dir. Note that this does mean these have already been generated by phing
 * before this deploy script is called.
 */
passthru(__DIR__ . '/.phing/vendor/bin/phing property:write-full');

require __DIR__ . '/.deployer/vendor/oneagency/deployer/bootstrap-properties.php';
require __DIR__ . '/.deployer/vendor/oneagency/deployer/drupal8-standard.php';
# require __DIR__ . '/.deployer/vendor/oneagency/deployer/drupal8-multisite_extension.php';