<?php

namespace Deployer;

// This is loaded in by the deployer.phar and is accessible.
use Deployer\Task\Context;

set('ssh_type', 'native');
set('ssh_multiplexing', true);

/* Set a basic set of properties based on the information in the /properties
 * dir. Note that this does mean these have already been generated by phing
 * before this deploy script is called.
 *
 * e.g: "phing properties:write-full"
 *
 * @TODO Make this less error prone by ensuring this some other way.
 */
require __DIR__ . '/.heavyd/vendor/heavyd/platform/lib/deployer/bootstrap-properties.php';
require __DIR__ . '/.heavyd/vendor/heavyd/platform/lib/deployer/drupal8-standard.php';
